---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: homarr
  namespace: flux-system
spec:
  image: ghcr.io/homarr-labs/homarr
  interval: 1m

---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: homarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homarr
  policy:
    semver:
      range: '>=0.0.0'