apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - apps-flux-sync.yaml
  - nginx-image.yaml
  - sonarr-image.yaml
  - jackett-image.yaml
  - prowlarr-image.yaml
