---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.86.50
    path: /volume1/k3s/monitoring/Grafana
  mountOptions:
    - nfsvers=4.0
    - noatime
    - lookupcache=all
    - timeo=600
    - retrans=2
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  volumeName: grafana-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.86.50
    path: /volume1/k3s/monitoring/Prometheus
  mountOptions:
    - nfsvers=4.0
    - noatime
    - lookupcache=all
    - timeo=600
    - retrans=2
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  volumeName: prometheus-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alloy-pv
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.86.50
    path: /volume1/k3s/monitoring/Alloy
  mountOptions:
    - nfsvers=4.0
    - noatime
    - lookupcache=all
    - timeo=600
    - retrans=2
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alloy-pvc
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  volumeName: alloy-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.86.50
    path: /volume1/k3s/monitoring/Loki
  mountOptions:
    - nfsvers=4.0
    - noatime
    - lookupcache=all
    - timeo=600
    - retrans=2
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  volumeName: loki-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-monitoring-pv
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.86.50
    path: /volume1/k3s/media/Jackett
  mountOptions:
    - nfsvers=4.0
    - noatime
    - lookupcache=all
    - timeo=600
    - retrans=2
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-monitoring-config
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  volumeName: jackett-monitoring-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-monitoring-pv
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.86.50
    path: /volume1/k3s/media/Sonarr
  mountOptions:
    - nfsvers=4.0
    - noatime
    - lookupcache=all
    - timeo=600
    - retrans=2
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-monitoring-config
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  volumeName: sonarr-monitoring-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi