apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - argocd
#  - bazarr
#  - flaresolverr
  - homarr
  - jackett
  - lidarr
#  - longhorn
  - prowlarr
#  - qbittorrent
#  - rancher
  - sonarr
#  - traefik
