apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lidarr-media-data-persistentVolume.yaml
  - lidarr-media-data-persistentVolumeClaim.yaml
  - lidarr-persistentVolume.yaml
  - lidarr-persistentVolumeClaim.yaml
  - lidarr-deployment.yaml
  - lidarr-service.yaml
  - lidarr-middleware-headers.yaml
  - lidarr-ingressroute.yaml
