apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-media-data
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  volumeName: "lidarr-media-data-pv"
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Ti
