apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jackett-persistentVolume.yaml
  - jackett-persistentVolumeClaim.yaml
  - jackett-deployment.yaml
  - jackett-service.yaml
#  - jackett-middleware-headers.yaml
#  - jackett-middleware-redirect--not-needed.yaml
#  - jackett-middleware-strip--not-needed.yaml
  - jackett-ingressroute.yaml
