apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - slskd-persistentVolume.yaml
  - slskd-persistentVolumeClaim.yaml
  - slskd-deployment.yaml
  - slskd-service.yaml
  - slskd-middleware-headers.yaml
  - slskd-ingressroute.yaml
