apiVersion: v1
kind: Service
metadata:
  name: slskd
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: slskd
  ports:
    - name: web
      port: 5030
      targetPort: 5030
    - name: soulseek
      port: 50300
      targetPort: 50300
      protocol: TCP
