apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`homarr.catacumbas69.com`)
      priority: 120
      kind: Rule
      services:
        - name: homarr
          port: 3000
      middlewares:
        - name: homarr-headers
