apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
        - name: homarr
          image: ghcr.io/homarr-labs/homarr:v1.59.3 # {"$imagepolicy": "flux-system:homarr"}
          ports:
            - containerPort: 7575
          env:
            - name: SECRET_ENCRYPTION_KEY
              value: "443aa238ee2f3acd3b537ea015cea35e8b3c92c7547199197221a7395b2aa745"
            - name: NEXTAUTH_URL_INTERNAL
              value: "http://homarr:7575"
            - name: NEXTAUTH_URL
              value: "http://homarr.catacumbas69.com:8080"
            - name: PUBLIC_URL
              value: "http://homarr.catacumbas69.com:8080"
            - name: NEXTAUTH_SECRET
              value: "YPCNoNRJ0rb/Ylho6jGxK8CZZ807Yyzly+iJVa2j1ak="
            - name: TRUST_PROXY
              value: "true"
          volumeMounts:
            - name: config
              mountPath: /appdata
            - name: icons
              mountPath: /app/public/icons
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homarr-config
        - name: icons
          emptyDir: {}
