apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-config
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  volumeName: "homarr-pv"
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi