apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sonarr-media-data-persistentVolume.yaml
  - sonarr-media-data-persistentVolumeClaim.yaml
  - sonarr-persistentVolume.yaml
  - sonarr-persistentVolumeClaim.yaml
  - sonarr-deployment-with_NFS.yaml
  - sonarr-service.yaml
#  - sonarr-middleware-headers.yaml
  - sonarr-ingressroute.yaml
