apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-media-data-pv
spec:
  capacity:
    storage: 40Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.86.50
    path: /volume1/Media
  mountOptions:
    - nfsvers=4.0
    - rsize=1048576
    - wsize=1048576
    - noatime
    - hard
