apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.86.50
    path: /volumeUSB4/usbshare
  mountOptions:
    - nfsvers=4.0
    - rsize=1048576
    - wsize=1048576
    - noatime
    - hard
