apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - soularr-persistentVolume.yaml
  - soularr-persistentVolumeClaim.yaml
  - soularr-configmap.yaml
  - soularr-deployment.yaml
  - soularr-service.yaml
  - soularr-ingressroute.yaml
