apiVersion: v1
kind: ConfigMap
metadata:
  name: soularr-configmap-config
  namespace: media
data:
  config.ini: |
    [Settings]
    log_to_file = True
    
    [Lidarr]
    api_key = 136e185aa709436aba0b3cdc064856e2
    host_url = http://lidarr.media.svc.cluster.local:8686
    download_dir = /downloads
    disable_sync = False

    [Slskd]
    api_key = 814728bfc19de7ec9f3608b4f7dbb0a7
    host_url = http://slskd.media.svc.cluster.local:5030
    url_base = /
    download_dir = /downloads/down/Temp/soulseek/downloads
    delete_searches = False
    stalled_timeout = 3600

    [Release Settings]
    use_most_common_tracknum = True
    allow_multi_disc = True
    accepted_countries = Portugal,Europe,Japan,United Kingdom,United States,[Worldwide],Australia,Canada
    accepted_formats = CD,Digital Media,Vinyl

    [Search Settings]
    search_timeout = 5000
    maximum_peer_queue = 50
    minimum_peer_upload_speed = 0
    allowed_filetypes = flac,mp3
    search_for_tracks = True
    album_prepend_artist = True
    minimum_filename_match_ratio = 0.8
