apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prowlarr-persistentVolume.yaml
  - prowlarr-persistentVolume.yaml
  - prowlarr-deployment.yaml
  - prowlarr-service.yaml
#  - prowlarr-middleware-headers.yaml
  - prowlarr-ingressroute.yaml
