apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.86.50
    path: /volume1/k3s/media/Prowlarr
  mountOptions:
    - nfsvers=4.0
    - noatime
    - lookupcache=all
    - timeo=600
    - retrans=2
    - hard
