apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prowlarr.catacumbas69.com`)
#    - match: PathPrefix(`/prowlarr`)
      priority: 100
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
#      middlewares:
#        - name: prowlarr-headers

